# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # master server
  config.vm.define "kmaster" do |kmaster|
    kmaster.vm.box = "debian/stretch64"
    kmaster.vm.hostname = "kmaster"
    kmaster.vm.box_url = "debian/stretch64"
    kmaster.vm.network "private_network", ip: "192.168.100.10"
    kmaster.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--name", "kmaster"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
	config.vm.provision "shell", inline: <<-SHELL
      sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
	  service ssh restart
    SHELL
  kmaster.vm.provision "shell", path: "install_common.sh"
  kmaster.vm.provision "shell", path: "install_master.sh"
  end
  
  
  #slave servers
  nbSlaves = 2
  (1..nbSlaves).each do |i|
    config.vm.define "knode#{i}" do |knode|
	  knode.vm.box = "debian/stretch64"
	  knode.vm.hostname = "knode#{i}"
	  knode.vm.network "private_network", ip: "192.168.100.1#{i}"
	  knode.vm.provider "virtualbox" do |v|
	    v.name = "knode#{i}"
		v.memory = 1024
		v.cpus = 1
	  end
	  config.vm.provision "shell", inline: <<-SHELL
	    sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
	    service ssh restart
	  SHELL
    knode.vm.provision "shell", path: "install_common.sh"
    knode.vm.provision "shell", path: "install_node.sh"
	end
  end
end
