Vagrant.configure(2) do |config|
	config.vm.define "nexus-box" do |nexusbox|
		nexusbox.vm.box = "ubuntu/xenial64"
    		nexusbox.vm.network "private_network", ip: "192.168.199.9"
    		nexusbox.vm.hostname = "nexus-box"
      		#nexusbox.vm.provision "shell", path: "scripts/install.sh"
    		nexusbox.vm.provider "virtualbox" do |v|
    		  v.memory = 2048
    		  v.cpus = 2
    		end
	end
end